export const categoriasEmpresas = [
  {
    nomeCategoria: "Produtos de Limpeza",
    empresas: [
      {
        nomeEmpresa: "EcoClean",
        imagemEmpresa: "/logos/logoEcoclean.jpg",
        endereco:
          "Av. Juscelino Kubitscheck de Oliveira, 3220 Matinhos - PR, CEP 83260-000",
        contato1: "(41) 99794-3219",
        contato2: "(41) 99988-0508",
        email: "ecocleanmatinhos@gmail.com",
        site: "www.ecocleanmatinhos.com.br",
        linkWhatsapp: "https://wa.me/5541997943219",
        linkTelefone: "tel:5541997943219",
        linkLocalizacao: "https://maps.app.goo.gl/KShU4NfQC3HcqGE2A",
        linkSite: "https://www.ecocleanmatinhos.com.br",
        linkInstagram: "https://www.instagram.com/ecocleanmatinhos/",
      },
      {
        nomeEmpresa: "Limpa Mais",
        imagemEmpresa: "/logos/logoLimpamais.jpg",
        endereco: "Rua São Matheus, , 1592 - Caiobá -83260-000 - Matinhos - PR",
        contato1: "(41) 3473-4006",
        contato2: "(41) 99229-4235",
        email: null,
        site: null,
        linkWhatsapp: "https://wa.me/5541992294235",
        linkTelefone: "tel:5541997943219",
        linkLocalizacao: "https://maps.app.goo.gl/adMpSDdAMCKExG117",
        linkSite: null,
        linkInstagram: "https://www.instagram.com/limpamais.matinhos/",
      },
    ],
  },
  {
    nomeCategoria: "Academias",
    empresas: [
      {
        nomeEmpresa: "Box Personal Cross",
        imagemEmpresa: "/logos/logoPersonalcross.jpg",
        endereco: "Av. Curitiba, 3109 - Bom Retiro 83260-000 - Matinhos - PR",
        contato1: "(41) 9964-5995",
        contato2: "(41) 99726-4645",
        email: "profguto_1106@hotmail.com",
        site: null,
        linkWhatsapp: "https://wa.me/554199645995",
        linkTelefone: "tel:554199645995",
        linkLocalizacao: "https://maps.app.goo.gl/ATQoJWjj9Jeji52VA",
        linkSite: null,
        linkInstagram: "https://www.instagram.com/boxpersonalcross/",
      },
    ],
  },
  {
    nomeCategoria: "Açougues",
    empresas: [
      {
        nomeEmpresa: "Açougue Dois Irmãos",
        imagemEmpresa: "/logos/logo2irmaos.jpg",
        endereco:
          "Av. Juscelino Kubitschek de Oliveira, 1780 - Caiobá 83260-000 - Matinhos - PR",
        contato1: "(41) 3473-1524",
        contato2: null,
        email: null,
        site: null,
        linkWhatsapp: null,
        linkTelefone: "tel:554134731524",
        linkLocalizacao: "https://maps.app.goo.gl/Dgwjt7YoDgwM5Sxa7",
        linkSite: null,
        linkInstagram: null,
      },
    ],
  },
  {
    nomeCategoria: "Arquitetura",
    empresas: [
      {
        nomeEmpresa: "Caiobá Arquitetura e Designe",
        imagemEmpresa: "/logos/logoCaiobaarquitetura.png",
        endereco:
          "AV. JUSCELINO KUBITSCHET DE OLIVEIRA, 1255 - CAIOBÁ 83260-000 - Matinhos - PR",
        contato1: "(41) 99790-8688",
        contato2: null,
        email: "caioba.arquitetura@gmail.com",
        site: "www.caiobaarquitetura.com/",
        linkWhatsapp: "https://wa.me/5541997908688",
        linkTelefone: "tel:5541997908688",
        linkLocalizacao: "https://maps.app.goo.gl/pqjAxMGn3tvYTTzD6",
        linkSite: "https://www.caiobaarquitetura.com/",
        linkInstagram: "https://www.instagram.com/caioba.arquitetura/",
      },
      {
        nomeEmpresa: "ARQMAX Arquitetura e Engenharia",
        imagemEmpresa: "/logos/logoArqmax.jpg",
        endereco:
          "AV JUSCELINO K DE OLIVEIRA, 3588 - CENTRO 83260-000 - Matinhos - PR",
        contato1: "(41) 3458-3783",
        contato2: "(41) 99672-1417",
        email: null,
        site: null,
        linkWhatsapp: "https://wa.me/5541996721417",
        linkTelefone: "tel:5541996721417",
        linkLocalizacao: "https://maps.app.goo.gl/5v5cRZ2xFpqCXFEA9",
        linkSite: null,
        linkInstagram: "https://www.instagram.com/arqmax_engmax/",
      },
      {
        nomeEmpresa: "Michel Lozovoy Arquitetura e Engenharia",
        imagemEmpresa: "/logos/logoMichelArq.png",
        endereco:
          "Av. Jucelino Kubitshek, 3634, sala 01 - Centro 83260-000 - Matinhos - PR",
        contato1: "(41) 99935-6454",
        contato2: null,
        email: "michellozovoyarquitetura@gmail.com",
        site: null,
        linkWhatsapp: "https://wa.me/5541999356454",
        linkTelefone: "tel:5541999356454",
        linkLocalizacao: "https://maps.app.goo.gl/vJmP18QxbmoZ91nAA",
        linkSite: null,
        linkInstagram: "https://www.instagram.com/michellozovoyarquitetura/",
      },
    ],
  },
  {
    nomeCategoria: "Cafés e Docerias",
    empresas: [
      {
        nomeEmpresa: "Celeiro da Gula",
        imagemEmpresa: "/logos/logoCeleiro.png",
        endereco: "R. Albano Muller, 188 - Centro 83260-000 - Matinhos - PR",
        contato1: "(41) 3473-1675",
        contato2: "(41) 99728-9610",
        email: "joseluisleal1980@gmail.com",
        site: null,
        linkWhatsapp: "https://wa.me/5541997289610",
        linkTelefone: "tel:554134731675",
        linkLocalizacao: "https://maps.app.goo.gl/X6xFYrC7Meok1FWv8",
        linkSite: null,
        linkInstagram: "https://www.instagram.com/celeirodagula_cafeteria/",
      },
      {
        nomeEmpresa: "Café da Mansa",
        imagemEmpresa: "/logos/logoCafeMansa.jpg",
        endereco:
          "Rua Presidente Kennedy, 361, Anexo V3 Imóveis - Praia Mansa 83260-000 - Matinhos - PR",
        contato1: "(41) 99604-3635",
        contato2: null,
        email: "andy.crfta@gmail.com",
        site: null,
        linkWhatsapp: "https://wa.me/5541996043635",
        linkTelefone: "tel:5541996043635",
        linkLocalizacao: "https://maps.app.goo.gl/A6RTtaReVNAyBpPf9",
        linkSite: null,
        linkInstagram: "https://www.instagram.com/cafedamansa/",
      },
    ],
  },
];
